codestates-seb/seb42_main_013

client/src/components/ScrollBar.js
client/src/components/SearchBar.js
client/src/pages/Suggest.js
client/src/styles/GlobalStyle.js

영양제 추천 페이지 초기 css 구현
- https://github.com/codestates-seb/seb42_main_013/issues/6

[Design] 영양제 추천 초기 css 구현

---

client/src/components/Footer.js
client/src/pages/Suggest.js

- Footer 초기 css 작업(그럴싸한 모양의 Footer 완성)
- 영양제 추천 탭 카드뉴스 폰트 크기 수정

[Design] Footer 초기 css 작업

---

client/src/pages/Mypage.js

- https://github.com/codestates-seb/seb42_main_013/issues/16

[Design] 마이페이지 CSS 

---

client/src/styles/GlobalStyle.js

[Design] 레이아웃 css 수정

---

client/src/components/Footer.js
client/src/styles/GlobalStyle.js

[Design]그림자 추가, 회색 변수 설정

---

client/src/components/DataInput.js
client/src/pages/MyPage.js
client/src/pages/SetUserInfo.js

- https://github.com/codestates-seb/seb42_main_013/issues/22

[Design] 유저 정보 입력 페이지

---

client/src/App.js
client/src/index.js

[Feat] router 경로 설정

---

client/src/App.js

router 설정 시 특정 화면에서 빈 공간 보이는 오류 수정

[Fix] router 설정 오류 수정

---

client/package-lock.json
client/package.json
client/src/components/ScrollBar.js
client/src/pages/Intro.js

Intro.js, ScrollBar.js의 슬라이드를 Swiper 라이브러리를 활용하여 구현

[Feat] 슬라이드 기능 구현(라이브러리 활용)

---

client/src/styles/GlobalStyle.js

[Design] a 태그 스타일 젼역 설정

---

client/src/pages/Intro.js

Intro 진행 중 (pull 오류 관련 테스트 위해 PR 열었음)

[Design] Intro 진행 중

---

client/package-lock.json
client/package.json
client/src/pages/Intro.js
client/src/styles/Buttons.js

Intro css 완성(초안)
버튼 hover, active 색상 rgba -> HEX 로 수정
- https://github.com/codestates-seb/seb42_main_013/issues/33

[Design] Intro css 초기 완성, 버튼 스타일 수정

---

client/src/App.js
client/src/components/Header.js
client/src/pages/Intro.js
client/src/pages/SignupDone.js
client/src/styles/Buttons.js

회원가입 완료 화면 css 및 기능 구현(로그인 페이지로 이동)
Header css 구현(화면마다 띄우는 아이콘 다름)
- https://github.com/codestates-seb/seb42_main_013/issues/43
- https://github.com/codestates-seb/seb42_main_013/issues/44

[Design] 회원가입 완료 화면 생성, Header 수정

---

client/package-lock.json
client/src/App.js
client/src/pages/SetUserInfo.js

[Design] setuserinfo 레이아웃 수정

---

client/.gitignore
client/package.json
client/src/App.js
client/src/components/Footer.js
client/src/components/Items.js
client/src/components/SearchBar.js
client/src/index.js
client/src/pages/Search.js
client/src/reducer/searchReducer.js
client/src/store/store.js

영양제 검색 기능 초기 구현
- https://github.com/codestates-seb/seb42_main_013/issues/56

[Feat] search 기능 초기 구현

---

client/package.json
client/src/components/Items.js
client/src/components/SearchBar.js
client/src/components/WebAside.js
client/src/pages/Search.js
client/src/pages/SetUserInfo.js
client/src/pages/Suggest.js

[Fix] 구현한 기능 오류 수정

---

client/package.json

[Fix] proxy 설정

---

client/src/App.js
client/src/pages/Intro.js
client/src/pages/MyPage.js
client/src/pages/SetUserInfo.js
client/src/styles/GlobalStyle.js

[Fix] 레이아웃 오류 수정

---

client/src/pages/Search.js
client/src/pages/Suggest.js

[Fix] 검색, 추천 기능 수정

---

client/src/components/Timeline.js
client/src/components/supplements.json
client/src/pages/CalendarPage.js
client/src/pages/Login.js

로그인 input창 수정 
- Login.js 컴포넌트
1. DataInput name props 추가
2. <LoginBox onSubmit={onSubmit} 삭제 CurrentBtn onClick={onSubmit} 추가
3. const onSubmit = asnyc() 변경

[Fix] Login.js 수정

---

client/package.json
client/src/components/Calendar.js
client/src/components/Timeline.js
client/src/components/supplements.json
client/src/pages/CalendarPage.js
client/src/pages/Login.js
client/src/pages/Signup.js

[Feat] Timeline.js 컴포넌트 수정
복용 기간, 복용 주기, 복용량에 따른 타임라인 표시

[Feat] Timeline.js 컴포넌트 수정

---

client/src/App.js
client/src/reducer/loginInfoReducer.js

[Feat] get user 기능 작업 중

---

client/src/App.js
client/src/components/ConcernSelector.js
client/src/pages/MyPage.js
client/src/pages/SetUserInfo.js
client/src/pages/Suggest.js
client/src/store/store.js

필수 정보 입력 기능 구현
추천 페이지 일부 수정(로그인한 닉네임 보임)

[Feat] 필수 정보 입력 초기 구현 및 추천 페이지 일부 수정

---

client/src/components/Header.js

- Header.js: `sessionStorage.removeItem('Authorization')` 추가

[Feat] Header.js 로그아웃

---

client/src/App.js
client/src/components/Header.js
client/src/components/ScrollBar.js
client/src/pages/Intro.js
client/src/pages/Login.js
client/src/pages/MyPage.js
client/src/pages/SetUserInfo.js
client/src/pages/Suggest.js
client/src/util/getUserInfo.js

[Feat] 페이지 진입 시 로그인 상태 확인 구현

---

client/src/App.js
client/src/pages/MyPage.js
client/src/pages/Search.js

새로고침 시 유저 정보 저장 관련 고민 및 코드 중간 저장

[Fix] 새로고침 관련 고민 및 중간 저장

---

client/src/pages/Login.js

[Feat] Login.js 유저 정보 저장

---

client/src/App.js
client/src/components/Header.js
client/src/pages/Login.js
client/src/pages/MyPage.js
client/src/pages/Search.js
client/src/pages/SetUserInfo.js
client/src/reducer/loginInfoReducer.js
client/src/util/getUserInfo.js

유저 정보 세션스토리지에 저장하는 기능 구현
- redux initialState를 세션스토리지 값 또는 false, null로 지정
- 상태 변경 생기면 세션스토리지에 저장 후 상태를 세션스토리지 값으로 지정

[Feat] 유저 정보 세션스토리지 저장 기능 구현

---

client/src/App.js
client/src/pages/Search.js
client/src/util/getUserInfo.js

로그인 만료 관련 코드 수정
(로그인 만료 / 로그인 유지 로 console.log 분리)

[Fix] 로그인 만료 관련 코드 수정

---

client/src/App.js
client/src/pages/Login.js
client/src/pages/MyPage.js
client/src/pages/Search.js
client/src/pages/SetUserInfo.js
client/src/pages/Signup.js
client/src/pages/SignupDone.js
client/src/pages/Suggest.js
client/src/util/useAuthCheck.js

- 필수 정보 입력 페이지에 나타난 오류 수정
- 토큰 유효기간을 검증하는 새로운 함수 구현 (유저 정보를 세션스토리지에 저장하게 되면서 필요할 것 같습니다)
- 마이페이지 유저 정보 UPDATE 구현
- https://github.com/codestates-seb/seb42_main_013/issues/102
- https://github.com/codestates-seb/seb42_main_013/issues/103

[Feat] 필수 정보 입력 오류 수정, 토큰 유효기간 검증 구현, 마이페이지 수정 구현

---

client/src/images/svg/loadingIcon.svg
client/src/pages/MyPage.js
client/src/pages/Search.js
client/src/pages/SetUserInfo.js
client/src/pages/SignupDone.js
client/src/pages/Suggest.js

검색 로딩 인디케이터 구현
닉네임, 건강고민 조건 추가(4자 이상, 1개 이상)
영양제 추천 -> 서버에서 받은 자료로 변경

[Feat] 검색 로딩 구현, 닉네임 건강고민 조건 추가, 추천 서버에서 받은 자료로 변경

---

client/src/pages/MyPage.js
client/src/pages/Search.js
client/src/pages/Suggest.js
client/src/util/useAuthCheck.js

토큰 유효기간 검증 함수 잘 되는 것 확인(추후 추가 에러 핸들링 필요할 수 있음)
추천 페이지 데이터 불러오기 테스트 중

[Feat] 토큰 유효기간 검증 함수 체크 완료, 추천 페이지 데이터 테스트

---

client/src/components/Health.js
client/src/components/ScrollBar.js
client/src/pages/MyPage.js
client/src/pages/Suggest.js

- 마이페이지 토큰 유효기간 관련 에러 핸들링(수정 버튼 눌렀을 때 유효기간 만료된 토큰일 경우 오류 띄우고 새로고침 시켜 시작 페이지로 이동)
- 추천 페이지 자료 프론트 더미데이터 -> DB 자료로 변경

[Fix] 마이페이지 토큰 유효기간 관련 에러 핸들링, 추천 페이지 DB 자료로 변경

---

client/src/components/ScrollBar.js
client/src/pages/MyPage.js
client/src/pages/SetUserInfo.js
client/src/pages/Suggest.js

[Feat] 과제 제출 전 중간 점검

---

client/src/components/Header.js
client/src/pages/Search.js

검색 페이지 필터 계속 수정 시 제대로 필터링 되지 않는 오류 수정
헤더 로고 클릭 시 이동 경로 분기하여 오류 나지 않도록 수정

[Fix] 검색 가격 필터 오류 수정, 헤더 로고 클릭 오류 수정

---

client/public/index.html
client/src/pages/Login.js
client/src/pages/Suggest.js

index.html 수정
유저 영양제 추천 코드 수정(최초 정보 받을 시 랜덤으로 배치 후 로그인 되어있는 동안 고정)

[Fix] index.html 수정, 유저 영양제 추천 코드 수정

---

client/src/components/Calendar.js
client/src/components/Footer.js
client/src/components/Timeline.js
client/src/pages/CalendarPage.js
client/src/pages/Login.js

- CalendarPage.js: 약 복용 정보 미 입력 시 빈 화면 수정

[Feat] 캘린더 페이지 수정

---

client/src/components/Calendar.js
client/src/components/DeleteConfirm.js
client/src/pages/CalendarPage.js
client/src/pages/Intro.js
client/src/pages/Login.js
client/src/pages/Search.js
client/src/pages/SetUserInfo.js
client/src/pages/Signup.js
client/src/pages/Suggest.js
client/src/util/deletePillData.js
client/src/util/postPillData.js
client/src/util/searchBycode.js
client/src/util/useAuthCheck.js

[Comment] 불필요한 콘솔로그 제거

---

client/src/pages/Login.js

로그인 코드 수정(window.loaction.href => navigate)

[Fix] 로그인 코드 수정

---

client/src/pages/MyPage.js
client/src/pages/Suggest.js

[Fix] 비로그인 시 인트로 이동 로직 수정

---

client/src/pages/Signup.js

[Fix] 회원가입 alert 삭제
